### PR TITLE
Add onboarding checklist

### PR DESCRIPTION
**Pull request by grst**
LMK if something is missing

### CODE REVIEW

**Comment by grst** [comment]
we have a linkedin account?

**Comment by Zethson** [comment]
https://www.linkedin.com/company/scverse/mycompany/?viewAsMember=true

**Comment by grst** [comment]
Ah, but you can anyway just add this to your profile as employer?

**Comment by Zethson** [comment]
Yes of course. But some of us have admin rights for the page. It's really not a big deal and I'm just memeing. We're not using it atm.

**Pull request merged**
